/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasprj.view;

import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.File;
import uasprj.model.*;
import uasprj.dao.FilmDAO;

/**
 *
 * @author Zandatsu
 */
public class AddFilm extends javax.swing.JFrame {

    /**
     * Creates new form AddFilm
     */
    public AddFilm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfId = new javax.swing.JTextField();
        tfJudul = new javax.swing.JTextField();
        tfGenre = new javax.swing.JTextField();
        tfDurasi = new javax.swing.JTextField();
        tfRating = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 130, -1));
        jPanel1.add(tfJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 130, -1));
        jPanel1.add(tfGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 130, -1));
        jPanel1.add(tfDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, -1));
        jPanel1.add(tfRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 120, -1));
        jPanel1.add(tfHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 120, -1));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backbutton3.png"))); // NOI18N
        BackButton.setBorder(null);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sAVE.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 110, 30));

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cLEAR.png"))); // NOI18N
        clearButton.setBorder(null);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 110, 30));

        saveButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AddFilm.png"))); // NOI18N
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 520));

        jButton3.setText("jButton3");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
// Konfirmasi dengan JOptionPane
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin kembali ke Dashboard?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        // Buka Dashboard
        Dashboard ds = new Dashboard();
        ds.setLocationRelativeTo(null);
        ds.setVisible(true);

        // Tutup frame saat ini
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String idStr = tfId.getText();
        String judul = tfJudul.getText();
        String genre = tfGenre.getText();
        String durasiStr = tfDurasi.getText();
        String ratingStr = tfRating.getText();
        String hargaStr = tfHarga.getText();
        
        if (judul.isEmpty() || genre.isEmpty() || durasiStr.isEmpty() || hargaStr.isEmpty()|| idStr.isEmpty() || ratingStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            double harga = Double.parseDouble(hargaStr);
            int durasi = Integer.parseInt(durasiStr);
            int id = Integer.parseInt(idStr);
            double rating = Double.parseDouble(ratingStr);

            // 3. Buat Object Film
            detFilm filmBaru = new detFilm();
            filmBaru.setIdFilm(id);
            filmBaru.setJudul(judul);
            filmBaru.setGenre(genre);
            filmBaru.setDurasi(durasi);
            filmBaru.setRating(rating);
            filmBaru.setHargaFilm(harga);
            
            FilmDAO dao = new FilmDAO();
            boolean sukses = dao.insert(filmBaru);
            
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data Film Berhasil Disimpan!");
                // Reset form
                tfId.setText("");
                tfJudul.setText("");
                tfGenre.setText("");
                tfDurasi.setText("");
                tfRating.setText("");
                tfHarga.setText("");
                
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
        
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        tfId.setText("");
        tfJudul.setText("");
        tfGenre.setText("");
        tfDurasi.setText("");
        tfRating.setText("");
        tfHarga.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel saveButton;
    private javax.swing.JTextField tfDurasi;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJudul;
    private javax.swing.JTextField tfRating;
    // End of variables declaration//GEN-END:variables
}