/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasprj.view;

import javax.swing.JOptionPane;

/**
 *
 * @author SomethingDelicious
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Avatar_Dashboard = new javax.swing.JButton();
        Agak_Laen_Dashboard = new javax.swing.JButton();
        Comic_8_Dashboard = new javax.swing.JButton();
        Zootopia_2_Dashboard = new javax.swing.JButton();
        Janur_Ireng_Dashboard = new javax.swing.JButton();
        BackToLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Avatar_Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Avatar_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/avatar.png"))); // NOI18N
        Avatar_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Avatar_DashboardActionPerformed(evt);
            }
        });
        getContentPane().add(Avatar_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 180, 310));

        Agak_Laen_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/agaklaen.png"))); // NOI18N
        Agak_Laen_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agak_Laen_DashboardActionPerformed(evt);
            }
        });
        getContentPane().add(Agak_Laen_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 180, 310));

        Comic_8_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/comic8.png"))); // NOI18N
        Comic_8_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comic_8_DashboardActionPerformed(evt);
            }
        });
        getContentPane().add(Comic_8_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 180, 310));

        Zootopia_2_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zootopia.png"))); // NOI18N
        Zootopia_2_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zootopia_2_DashboardActionPerformed(evt);
            }
        });
        getContentPane().add(Zootopia_2_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, 180, 310));

        Janur_Ireng_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/janurireng.png"))); // NOI18N
        Janur_Ireng_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Janur_Ireng_DashboardActionPerformed(evt);
            }
        });
        getContentPane().add(Janur_Ireng_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 180, 310));

        BackToLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/backbutton3.png"))); // NOI18N
        BackToLogin.setBorder(null);
        BackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dasboard.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Avatar_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Avatar_DashboardActionPerformed
    //menampilkan halaman
    Film_Avatar fa = new Film_Avatar();
    fa.setVisible(true);
    //loacation
    fa.setLocationRelativeTo(null);
    //menutup frame
    this.dispose();
    }//GEN-LAST:event_Avatar_DashboardActionPerformed

    private void Agak_Laen_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agak_Laen_DashboardActionPerformed
     // menampilkan halaman
    Film_agak_lain al = new Film_agak_lain();
    al.setVisible(true);
    //location
    al.setLocationRelativeTo(null);
    //menutup frame
    this.dispose();
    }//GEN-LAST:event_Agak_Laen_DashboardActionPerformed

    private void Janur_Ireng_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Janur_Ireng_DashboardActionPerformed
     // menampilkan halaman
    Film_Janur_Ireng ji = new Film_Janur_Ireng();
    ji.setVisible(true);
    //location
    ji.setLocationRelativeTo(null);
    //menutup frame
    this.dispose();
    }//GEN-LAST:event_Janur_Ireng_DashboardActionPerformed

    private void BackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLoginActionPerformed
     // Konfirmasi dengan JOptionPane
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin kembali ke Login?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        // Buka LoginFrame
        LoginFrame login = new LoginFrame();
        login.setLocationRelativeTo(null);
        login.setVisible(true);

        // Tutup frame saat ini
        this.dispose();
    }
   // TODO add your handling code here:
    }//GEN-LAST:event_BackToLoginActionPerformed

    private void Comic_8_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comic_8_DashboardActionPerformed
//menampilkan halaman
    Film_Comic_8 c8 = new Film_Comic_8();
    c8.setVisible(true);
    //loacation
    c8.setLocationRelativeTo(null);
    //menutup frame
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Comic_8_DashboardActionPerformed

    private void Zootopia_2_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zootopia_2_DashboardActionPerformed
//menampilkan halaman
    Film_Zootopia_2 zt = new Film_Zootopia_2();
    zt.setVisible(true);
    //loacation
    zt.setLocationRelativeTo(null);
    //menutup frame
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Zootopia_2_DashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agak_Laen_Dashboard;
    private javax.swing.JButton Avatar_Dashboard;
    private javax.swing.JButton BackToLogin;
    private javax.swing.JButton Comic_8_Dashboard;
    private javax.swing.JButton Janur_Ireng_Dashboard;
    private javax.swing.JButton Zootopia_2_Dashboard;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
