/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasprj.view;

import javax.swing.JOptionPane;
import uasprj.model.Transaksi;
import uasprj.dao.TransaksiDAO;
import uasprj.util.HargaFormatter;
/**
 *
 * @author SomethingDelicious
 */
public class Pembayaran extends javax.swing.JFrame {

    private Transaksi transaksi;
    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
    }
    public Pembayaran(Transaksi tr) {
        initComponents();
        this.transaksi = tr;
        
        // Tampilkan total harga saat form dibuka
        lblTotal.setText(HargaFormatter.formatRupiah(transaksi.getTotalBayar()));
        lblKembalian.setText("Rp 0"); // Reset kembalian
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        lblKembalian = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("Rp. 0");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, 40));
        jPanel1.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 240, 30));

        lblKembalian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKembalian.setForeground(new java.awt.Color(255, 255, 255));
        lblKembalian.setText("Rp. 0");
        jPanel1.add(lblKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buttonPay.png"))); // NOI18N
        btnBayar.setText("jButton1");
        btnBayar.setBorder(null);
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buktiPembayaran.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil input uang
            String input = txtBayar.getText().replaceAll("[^0-9]", ""); // Hanya ambil angka
            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan nominal uang!");
                return;
            }

            double uangBayar = Double.parseDouble(input);
            double totalBelanja = transaksi.getTotalBayar();

            // 2. Cek apakah uang cukup
            if (uangBayar < totalBelanja) {
                JOptionPane.showMessageDialog(this, 
                    "Uang Kurang! \nKurang: " + HargaFormatter.formatRupiah(totalBelanja - uangBayar),
                    "Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 3. Hitung Kembalian
            double kembalian = uangBayar - totalBelanja;
            lblKembalian.setText(HargaFormatter.formatRupiah(kembalian));

            // 4. Simpan Transaksi ke Database
            transaksi.setMetodePembayaran("Cash");
            // (Opsional: Simpan info uang bayar/kembalian di objek transaksi jika mau dicatat)
            
            TransaksiDAO dao = new TransaksiDAO();
            dao.simpanTransaksi(transaksi); //

            // 5. Sukses -> Buka Struk
            JOptionPane.showMessageDialog(this, "Pembayaran Berhasil!");
            
            // Oper data transaksi (yang sudah punya ID dari DB) & info pembayaran ke StrukForm
            StrukForm struk = new StrukForm(transaksi, uangBayar, kembalian);
            struk.setVisible(true);
            struk.setLocationRelativeTo(null);
            
            this.dispose(); // Tutup form pembayaran

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input uang harus angka valid!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtBayar;
    // End of variables declaration//GEN-END:variables
}
