/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasprj.view;

/**
 *
 * @author SomethingDelicious
 */
public class PemesananTiketForm extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    public PemesananTiketForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        cbJadwal = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        rbWeekend = new javax.swing.JRadioButton();
        rbWeekday = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        confirm = new javax.swing.JToggleButton();
        lblTotal = new javax.swing.JLabel();
        chkA1 = new javax.swing.JCheckBox();
        chkA2 = new javax.swing.JCheckBox();
        chkA3 = new javax.swing.JCheckBox();
        chkA4 = new javax.swing.JCheckBox();
        chkA5 = new javax.swing.JCheckBox();
        chkB1 = new javax.swing.JCheckBox();
        chkB2 = new javax.swing.JCheckBox();
        chkB3 = new javax.swing.JCheckBox();
        chkB4 = new javax.swing.JCheckBox();
        chkB5 = new javax.swing.JCheckBox();
        chkC1 = new javax.swing.JCheckBox();
        chkC2 = new javax.swing.JCheckBox();
        chkC3 = new javax.swing.JCheckBox();
        chkC4 = new javax.swing.JCheckBox();
        chkC5 = new javax.swing.JCheckBox();
        chkVIP1 = new javax.swing.JCheckBox();
        chkVIP2 = new javax.swing.JCheckBox();
        chkVIP3 = new javax.swing.JCheckBox();
        chkVIP4 = new javax.swing.JCheckBox();
        chkVIP5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbJadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00", "14:35", "17:00", "19:45" }));
        cbJadwal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbJadwalComponentAdded(evt);
            }
        });
        getContentPane().add(cbJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 190, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 12, -1, -1));

        buttonGroup1.add(rbWeekend);
        rbWeekend.setBorder(null);
        rbWeekend.setMaximumSize(new java.awt.Dimension(200, 41));
        rbWeekend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWeekendActionPerformed(evt);
            }
        });
        getContentPane().add(rbWeekend, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 20, 20));

        buttonGroup1.add(rbWeekday);
        rbWeekday.setBorder(null);
        rbWeekday.setMaximumSize(new java.awt.Dimension(150, 30));
        rbWeekday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWeekdayActionPerformed(evt);
            }
        });
        getContentPane().add(rbWeekday, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 20, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("0");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, 20));

        confirm.setBackground(new java.awt.Color(102, 51, 0));
        confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/confirm.png"))); // NOI18N
        confirm.setBorder(null);
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 150, -1));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setText("0");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 30, -1));
        getContentPane().add(chkA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));

        chkA2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(chkA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));
        getContentPane().add(chkA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        chkA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkA4ActionPerformed(evt);
            }
        });
        getContentPane().add(chkA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));
        getContentPane().add(chkA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));
        getContentPane().add(chkB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        chkB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkB2ActionPerformed(evt);
            }
        });
        getContentPane().add(chkB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));
        getContentPane().add(chkB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));
        getContentPane().add(chkB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));
        getContentPane().add(chkB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));
        getContentPane().add(chkC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));
        getContentPane().add(chkC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));
        getContentPane().add(chkC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));
        getContentPane().add(chkC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));
        getContentPane().add(chkC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));
        getContentPane().add(chkVIP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));
        getContentPane().add(chkVIP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));
        getContentPane().add(chkVIP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));
        getContentPane().add(chkVIP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));
        getContentPane().add(chkVIP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/WhatsApp Image 2026-01-13 at 16.10.57.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 360, 40));

        lblQty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Transaksi.jpeg"))); // NOI18N
        lblQty.setText("jLabel1");
        getContentPane().add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJadwalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbJadwalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJadwalComponentAdded

    private void rbWeekendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWeekendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbWeekendActionPerformed

    private void rbWeekdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWeekdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbWeekdayActionPerformed

    private void chkA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkA4ActionPerformed

    private void chkB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkB2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananTiketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananTiketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananTiketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananTiketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananTiketForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JComboBox<String> cbJadwal;
    private javax.swing.JCheckBox chkA1;
    private javax.swing.JCheckBox chkA2;
    private javax.swing.JCheckBox chkA3;
    private javax.swing.JCheckBox chkA4;
    private javax.swing.JCheckBox chkA5;
    private javax.swing.JCheckBox chkB1;
    private javax.swing.JCheckBox chkB2;
    private javax.swing.JCheckBox chkB3;
    private javax.swing.JCheckBox chkB4;
    private javax.swing.JCheckBox chkB5;
    private javax.swing.JCheckBox chkC1;
    private javax.swing.JCheckBox chkC2;
    private javax.swing.JCheckBox chkC3;
    private javax.swing.JCheckBox chkC4;
    private javax.swing.JCheckBox chkC5;
    private javax.swing.JCheckBox chkVIP1;
    private javax.swing.JCheckBox chkVIP2;
    private javax.swing.JCheckBox chkVIP3;
    private javax.swing.JCheckBox chkVIP4;
    private javax.swing.JCheckBox chkVIP5;
    private javax.swing.JToggleButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbWeekday;
    private javax.swing.JRadioButton rbWeekend;
    // End of variables declaration//GEN-END:variables
}
